name: Sync APK and Release Info

on:
  schedule:
    # 每天UTC时间00:00自动检查新release，可以根据需要调整cron表达式
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 允许手动触发workflow

jobs:
  sync-apk-and-release-info:
    runs-on: ubuntu-latest
    steps:
      # 获取最新发布的信息并推送到仓库
      - name: Get latest release info
        run: |
          # 使用GitHub API获取最新发布信息
          LATEST_RELEASE=$(curl -s "https://api.github.com/repos/chenzyadb/CuprumTurbo-Scheduler/releases/latest" | jq -r '.tag_name')
          if [ -n "$LATEST_RELEASE" ]; then
            echo "Latest Release: $LATEST_RELEASE"
            curl -s "https://api.github.com/repos/chenzyadb/CuprumTurbo-Scheduler/releases/latest" | jq '.' > release_info.json
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add release_info.json
            git commit -m "Update release info"
            git push origin HEAD:main
          else
            echo "No release found."
          fi